apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts/
    targetRevision: 12.1.0
    chart: velero
    helm:
      releaseName: velero
      values: |
        image:
          repository: velero/velero
          tag: v1.18.1
          pullPolicy: IfNotPresent

        configuration:
          providers:
            - aws
          backupStorageLocations:
            - provider: aws
              default: true
              credential:
                name: cloud
                key: cloud
              objectStorage:
                bucket: sdp-backups-hel1
              config:
                region: hel1-dc2
                s3Url: https://hsn.hel1.cloud.netapp.com
                s3ForcePathStyle: "true"
                insecureSkipTLSVerify: false
          volumeSnapshotLocations: []

        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.14.2
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins

        credentials:
          useSecret: false
          existingSecret: cloud

        restic:
          enable: true
          privileged: false

        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi

        resticResources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi

        logLevel: info
        deploySchedule: false
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m