apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/traefik
  - ../../base/longhorn
  - ../../base/velero
  - ../../base/test-backup

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: argocd