# apps/environments/dev/root-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sdp-root
  namespace: argocd
spec:
  project: default
  source:
    path: apps/environments/dev
    repoURL: https://github.com/DanKHansen/SDP.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/audit: baseline